# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16KEPe28s8WEpkQy5FpsKZ34Gyb_SdvnY
"""

Maior_numero = 0
for contador in range(5):
 numero = int (input ("digite o primeiro numero"))
if numero > Maior_numero:
 Maior_numero = numero

 print(Maior_numero)

for contador in range(1000, 2001):
  if contador % 11 == 2:
    print(contador)

soma = 0
for i in range(5):
  numero = float(input(f"digite o {i+1}º numero: "))
  soma += numero
media = soma/5
print(f"A soma dos numeros e: {soma}")
print(f"a media dos numeros e: {media}")

numero = int(input("Digite um número para calcular a tabuada: "))

# Calcula e mostra a tabuada usando um laço de repetição
print("Tabuada de", numero, ":")
for i in range(3, 11):
    resultado = numero * i
    print(numero, "x", i, "=", resultado)

# Calcula e mostra a tabuada usando um laço de repetição
for i in range(1, 11):
  for j in range(1, 11):
    resultado = i * j
    print(i, "x", j, "=", resultado)

for i in range (1,21):
  print(i)

for i in range(1,51):
  if i % 2 == 1:
    print(i)

def numeros_no_intervalo(a, b):
    if a < b:
        intervalo = range(a + 1, b)
    else:
        intervalo = range(b + 1, a)

    return list(intervalo)

a = int(input("Digite o primeiro número inteiro: "))
b = int(input("Digite o segundo número inteiro: "))

numeros = numeros_no_intervalo(num1, num2)
print("Números no intervalo:", numeros)

lojaB = 54000
lojaA = 0

for i in range(5):
  valor = int(input("digite um valor"))
  lojaA += valor

if lojaB > lojaA:
  print("Loja b foi maior")
elif lojaB == lojaA:
  print("foi igual")
else:
  print("loja A foi maior")

for i in range(10):
  numeros = input("digite um numero")
  if i % 2 == 1:
    print(i)
    print("esses numero sao impares")
  else:
    print("esses numeros sao pares")



nota = int(input("digite uma nota de 1 a 10"))
if  nota > 0 and nota < 10:
 print("nota valida")
else:
  print("nota invalida, digite uma nota de 0 a 10")

valordacompra = input("digite o valor a compra")

if valordacompra == 500:
  print("voce recebe 1% de desconto")
elif valordacompra == 600:
  print("voce recebeu 2% de desconto")
elif valordacompra == 700:
  print("voce recebeu 3% de desconto")
elif valordacompra == 800:
  print("voce recebeu 4% de desconto")
elif valordacompra == 900:
  print("voce recebeu 5% de desconto")
elif valordacompra == 1000:
  print("voce recebeu 6% de desconto")
elif valordacompra == 1100:
  print("voce recebeu 7% de desconto")
elif valordacompra == 1200:
  print("voce recebeu 8% de desconto")
elif valordacompra == 1300:
  print("voce recebeu 9% de desconto")
elif valordacompra == 1400:
  print("voce recebeu 10% de desconto")
elif valordacompra == 1500:
  print("voce recebeu 11% de desconto")
elif valordacompra == 1600:
  print("voce recebeu 12% de desconto")
elif valordacompra == 1700:
  print("voce recebeu 13% de desconto")
elif valordacompra == 1800:
  print("voce recebeu 14% de desconto")
elif valordacompra == 1900:
  print("voce recebeu 15% de desconto")
elif valordacompra == 2000:
  print("voce recebeu 16% de desconto")
elif valordacompra == 2100:
  print("voce recebeu 17% de desconto")
elif valordacompra == 2200:
  print("voce recebeu 18% de desconto")
elif valordacompra == 2300:
  print("voce recebeu 19% de desconto")
elif valordacompra == 2400:
  print("voce recebeu 20% de desconto")
elif valordacompra == 2500:
  print("voce recebeu 21% de desconto")
elif valordacompra == 2600:
  print("voce recebeu 22% de desconto")
elif valordacompra == 2700:
  print("voce recebeu 23% de desconto")
elif valordacompra == 2800:
  print("voce recebeu 24% de desconto")
elif valordacompra == 2900:
  print("voce recebeu 25% de desconto")

ate15 = 0
de16ate30 = 0
de31ate45 = 0
de46ate60 = 0
mais60 = 0
for i in range(15):
  idade = int(input("Digite sua idade"))
  if idade >= 15:
    ate15 += idade
  elif idade >= 16 and idade <=30:
    de16ate30 +=idade
  elif idade >= 31 and idade <= 45:
    de31ate45 +=idade
  elif idade >= 46 and idade <= 60:
    de46ate60 +=idade
  else:
    mais60 +=idade
print(f"Quantidade de pessoas com idade ate 15 anos = {ate15} / Quantidade de pessoas com idade de 16 ate 30 {de16ate30}\ quantidade de pessoas com 31 ate45 {de31ate45}/ quantidade de pessoas com ate 45 ate 60 {de46ate60}/ quantidades de pessoas com mais 60 {mais60}")

base = float(input("Digite a base: "))
expoente = int(input("Digite o expoente: "))

resultado = 1

for _ in range(expoente):
    resultado *= base

print(f"{base} elevado a {expoente} é igual a {resultado}")

N = int(input("Digite um número inteiro "))
primos = []
divisoes = 0

for num in range(2, N + 1):
    primo = True
    for i in range(2, int(num**0.5) + 1):
        divisoes += 1
        if num % i == 0:
            primo = False
            break
    if primo:
        primos += [num]

print("Números primos entre 1 e", N, primos)
print("Número total de divisões realizadas:", divisoes)